bear-blog/account-hierarchy/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

bear-blog/account-hierarchy/objects/Account/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bear-blog/main/default/objects/Account/fields/RootAccountId__c.field-meta.xml
<CustomField>
    <fullName>RootAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Root Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>ChildAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

bear-blog/account-hierarchy/classes/AccountSelector.cls
public inherited sharing class AccountSelector {
	public static AccountSelector newInstance() {
		//To be covered another day
		//return (AccountSelector) ClassFactory.newInstance(AccountSelector.class);
		return new AccountSelector();
	}

	protected String fieldsString;

	public AccountSelector() {
		this.fieldsString = getFieldsString();
	}

	public List<Account> selectById(Set<Id> accountIds) {
		String query = String.format(
			'SELECT {0} FROM Account WHERE Id IN :accountIds WITH SECURITY_ENFORCED ORDER BY Name',
			new List<String>{ this.fieldsString }
		);
		return (List<Account>) Database.query(query);
	}

	public List<Account> selectByParentId(Set<Id> parentIds) {
		String query = String.format(
			'SELECT {0} FROM Account WHERE ParentId IN :parentIds WITH SECURITY_ENFORCED ORDER BY ParentId, Name',
			new List<String>{ this.fieldsString }
		);
		return (List<Account>) Database.query(query);
	}

	public List<Account> selectByRootAccountId(Set<Id> rootAccountIds) {
		String query = String.format(
			'SELECT {0} FROM Account WHERE RootAccountId__c IN :rootAccountIds WITH SECURITY_ENFORCED ORDER BY RootAccountId__c, Name',
			new List<String>{ this.fieldsString }
		);
		return (List<Account>) Database.query(query);
	}

	public List<Account> selectByName(Set<String> names) {
		String query = String.format(
			'SELECT {0} FROM Account WHERE Name IN :names WITH SECURITY_ENFORCED ORDER BY Name',
			new List<String>{ this.fieldsString }
		);
		return (List<Account>) Database.query(query);
	}

	public List<Account> selectByNameNot(Set<String> names) {
		String query = String.format(
			'SELECT {0} FROM Account WHERE Name NOT IN :names WITH SECURITY_ENFORCED ORDER BY Name',
			new List<String>{ this.fieldsString }
		);
		return (List<Account>) Database.query(query);
	}

	public List<Account> selectByNameLike(String nameFilter) {
		String query = String.format(
			'SELECT {0} FROM Account WHERE Name LIKE :nameFilter WITH SECURITY_ENFORCED ORDER BY Name',
			new List<String>{ this.fieldsString }
		);
		return (List<Account>) Database.query(query);
	}

	public List<Account> selectByNameNotLike(String nameFilter) {
		String query = String.format(
			'SELECT {0} FROM Account WHERE NOT Name LIKE :nameFilter WITH SECURITY_ENFORCED ORDER BY Name',
			new List<String>{ this.fieldsString }
		);
		return (List<Account>) Database.query(query);
	}

	private String getFieldsString() {
		String fieldsString = '';
		for (Schema.SObjectField field : getSObjectFieldList()) {
			fieldsString += field.getDescribe().getName() + ', ';
		}
		return fieldsString.removeEnd(', ');
	}

	private List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField>{
			Account.Id,
			Account.ParentId,
			Account.RootAccountId__c,
			Account.Name,
			Account.Classification__c,
			Account.Priority__c
		};
	}
}